name: Build APK from Source Zip

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure unzip exists
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip source
        run: |
          unzip -q HadithDaily_Source.zip -d src
          ls -la src

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Installe Gradle 8.4 (compatible avec AGP 8.2.x)
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.4

      # Génère le wrapper avec
